name: plug-in_tentorium
version: '${project.version}'
main: me.turtle.plugintentorium.Plug_in_tentoruim
api-version: '1.20'
load: STARTUP
authors: [turtle]
description: a plug-in for Tentorium server
commands:
  hub:
    description: teleports you to the hub
    usage: /<command>

  knockback:
    description: teleports you to the knockback arena
    usage: /<command>

  tntrun:
    description: teleports you to tntrun
    usage: /<command>

  spleef:
    description: teleports you to spleef
    usage: /<command>

  parkour:
    description: teleports you to parkour
    usage: /<command>

  ffa:
    description: teleports you to ffa
    usage: /<command>
